### PR TITLE
chore: Adding code owners to the repo

### PR DESCRIPTION
**Pull request by rdenadai**
Adicionando code owners na parada, assim os reviewers já são notificados

### CODE REVIEW

**Review by mattpsvreis — DISMISSED** [review]
add @mattpsvreis >:(

**Comment by rdenadai** [comment]
> add @mattpsvreis >:(

Added!!!

**Review by mattpsvreis — APPROVED** [review]
LGTM!

**Comment by ryukinix** [comment]
Ideia boa demais @rdenadai

**Review by ryukinix — APPROVED** [review]
LGTM

**Pull request merged**
